# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = ENV['MAILJET_API_KEY']
  config.secret_key = ENV['MAILJET_SECRET_KEY']
  config.default_from = 'trouvetatable@yopmail.com'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end

# variable = Mailjet::Send.create(messages: [{
#   'From'=> {
#       'Email'=> 'trouvetatable@yopmail.com  ',
#       'Name'=> 'Me'
#   },
#   'To'=> [
#       {
#           'Email'=> 'oiboi3@yopmail.com',
#           'Name'=> 'You'
#       }
#   ],
#   'Subject'=> 'My first Mailjet Email!',
#   'TextPart'=> 'Greetings from Mailjet!',
#   'HTMLPart'=> 'Ça marche mais'
# }]
# )
# p variable.attributes[:messages]